export { default as AboutScreen } from './About'
export { default as FeedbackScreen } from './Feedback'
export { default as LanguageScreen } from './Language'
export { default as SettingScreen } from './Setting'
export { default as ThemeScreen } from './Theme'

export { default as CacheSettingScreen } from './CacheSetting'
export { default as ChangeLogScreen } from './ChangeLog'
export { default as HowToUseScreen } from './HowToUse'
export { default as OpenSourceScreen } from './License'
export { default as PrivacyScreen } from './Privacy'
export { default as SiteStatScreen } from './SiteStat'
export { default as URLSchemesScreen } from './URLSchemes'
export { default as TermsOfServiceScreen } from './TermsOfService'
